spring:
  application:
    name: student-service

  r2dbc:
    username: student_user
    password: ${SCHOOL_DB_PASSWORD:student_pwd}
    properties:
      schema: student_schema
    url: r2dbc:postgresql://${DB_HOST:localhost}:5432/emis_db?schema=student_schema
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10


  flyway:
    user: student_user
    password: ${FLYWAY_DB_PASSWORD:student_pwd}
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/emis_db
    schemas: student_schema
    default-schema: student_schema
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false

  cloud:
    function:
      definition:  attendanceEvents;studentReportEvents
    stream:
      bindings:
        attendanceEvents-in-0:
          destination: attendance.events.v1
          group: student-service-group

        studentReportEvents-in-0:
          destination: student-report.events.v1
          group: student-report-group

        studentReportEvents-out-0:
          destination: student-report.events.v1

      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}


    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/emis

        client:
          registration:
            student-service:
              client-id: emis-student-service
              client-secret: ${STUDENT_SERVICE_SECRET:secret}
              authorization-grant-type: client_credentials
              scope: openid
          provider:
            keycloak:
              issuer-uri: http://localhost:8080/realms/emis


  lifecycle:
    timeout-per-shutdown-phase: 15s

emis:
  services:
    configuration:
      base-url: ${EMIS_SERVICE_URL:http://localhost:8082}
      get-school-details-url: ${emis.services.configuration.base-url}/api/v1/schools/{schoolCode}
      validate-school-exists-url: ${emis.service.configuration.base-url}/schools/validate/{schoolCode}

    storage-base-url: ${EMIS_STORAGE_URL:http://localhost:8086/reports}

    timeout: 5
    actions:
      create-student:
        roles:
          - SYSTEM_ADMIN
          - STATE_ADMIN
          - SCHOOL_ADMIN

      view-student:
       roles:
         - SYSTEM_ADMIN
         - STATE_ADMIN
         - SCHOOL_ADMIN
         - SCHOOL_TEACHER
         - STUDENT
         - PARENT




server:
  port: 8083
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s


springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.converter: DEBUG
    org.springframework.validation: DEBUG
    org.springframework.web.reactive.result.method.annotation: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG